name: Build and Publish CFnat-Windows-GUI

on:
  push:
    branches:
      - master  # 触发主分支的推送事件
  pull_request:
    branches:
      - master  # 触发主分支的 PR 事件
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: windows-latest  # 使用 Windows 环境构建

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 获取源代码

    - name: Install .NET SDK and Visual Studio Build Tools
      run: |
        # 安装 .NET SDK 和 Visual Studio Build Tools
        choco install dotnet --version 6.0.100  # 安装指定版本的 .NET SDK
        choco install visualstudio2019buildtools --version 16.11.3  # 安装 Visual Studio 2019 Build Tools

    - name: Add MSBuild to PATH
      run: |
        # 显式将 Visual Studio MSBuild 路径添加到环境变量中
        echo "##[add-path]C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\MSBuild\\Current\\Bin" >> $GITHUB_ENV  # 添加 Visual Studio 2019 BuildTools MSBuild 路径
        echo "##[add-path]C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\MSBuild\\Current\\Bin" >> $GITHUB_ENV  # 添加 Visual Studio 2022 MSBuild 路径

    - name: Check MSBuild path
      run: |
        # 输出 MSBuild 的路径，确保 msbuild 命令可用
        where msbuild

    - name: Restore NuGet packages
      run: |
        nuget restore cfnat.win.gui.sln  # 恢复 NuGet 包

    - name: Build the project using the solution file
      run: |
        # 使用 .sln 文件来构建项目，指定配置和平台
        msbuild cfnat.win.gui.sln /p:Configuration=Release /p:Platform=x64

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: cfnat-windows-gui
        path: ./bin/Release  # 上传构建结果
