name: Build and Publish CFnat-Windows-GUI

on:
  push:
    branches:
      - master  # 将分支名称更新为 master
  pull_request:
    branches:
      - master
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: windows-latest  # 使用 Windows 环境构建

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 检出当前代码

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0'  # 设置 .NET SDK 版本（根据实际需求修改）

    - name: Restore dependencies
      run: dotnet restore  # 恢复 NuGet 包

    - name: Build project
      run: dotnet build --configuration Release  # 编译项目（不使用 --runtime）

    - name: Publish project
      run: dotnet publish --configuration Release --runtime win-x64 --self-contained true --output ./publish  # 发布为 x64 自包含应用

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: cfnat-windows-gui
        path: ./publish  # 将构建结果上传为构建工件
