name: Build and Publish CFnat-Windows-GUI

on:
  push:
    branches:
      - master  # 触发主分支的推送事件
  pull_request:
    branches:
      - master  # 触发主分支的 PR 事件
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: windows-latest  # 使用 Windows 环境构建

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 检出当前代码

    - name: Setup MSBuild
      run: |
        # 安装必要的构建工具，如 Visual Studio Build Tools
        choco install visualstudio2019buildtools --version 16.11.3

    - name: Restore NuGet packages
      run: |
        nuget restore cfnat.win.gui.sln  # 恢复 NuGet 包

    - name: Build the project
      run: |
        msbuild cfnat.win.gui.csproj /p:Configuration=Release /p:Platform=x64  # 使用 MSBuild 编译项目

    - name: Publish the project
      run: |
        msbuild cfnat.win.gui.csproj /p:Configuration=Release /p:Platform=x64 /p:DeployOnBuild=true /p:PublishProfile=FolderProfile /p:PublishDir=./publish  # 发布项目

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: cfnat-windows-gui
        path: ./publish  # 将构建结果上传为构建工件
