name: Build CFnat-Windows-GUI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true

      - name: Check MSYS2 environment
        run: |
          # 确认 MSYS2 环境和 pacman 是否可用
          pacman -V
          pacman -Syy  # 强制同步数据库
          
      - name: Install dependencies
        run: |
          # 确保 pacman 可以安装依赖
          pacman -S --noconfirm base-devel mingw-w64-x86_64-toolchain mingw-w64-x86_64-qt5

      - name: Build project
        run: |
          # 假设使用 CMake 构建
          cmake -G "MSYS Makefiles" .
          make

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cfnat-windows-gui-artifacts
          path: ./path/to/built/output  # 修改为实际的构建输出路径
