name: Build CFnat-Windows-GUI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest  # 使用最新的 Windows 环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 检出仓库代码

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true

      - name: Install dependencies
        run: |
          pacman -S --noconfirm base-devel mingw-w64-x86_64-toolchain

      - name: Install additional libraries (if needed)
        run: |
          pacman -S --noconfirm mingw-w64-x86_64-qt5  # 假设项目使用了 Qt

      - name: Build project
        run: |
          # 假设你使用的是 CMake 和 Qt 进行构建
          cmake -G "MSYS Makefiles" .
          make

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cfnat-windows-gui-artifacts
          path: ./path/to/built/output  # 指定构建输出目录
